apiVersion: v3
kind: system
spec:
  lifecycle: production
  tier: critical
  components:
    - service:django-celery-app
    - service:postgres
    - queue:redis
    - datastore:defaultdb
metadata:
  name: my-django-celery-app
  owner: app-team
  additionalOwners:
    - name: database-team
      type: operator
---
apiVersion: v3
kind: datastore
metadata:
  name: defaultdb
  additionalOwners:
    - name: db-team
      type: operator
---
apiVersion: v3
kind: service
metadata:
  name: django-celery-app
  additionalOwners:
    - name: app-team
      type: operator
---
apiVersion: v3
kind: queue
metadata:
  name: redis
---
apiVersion: v3
kind: service
metadata:
  name: postgres
