apiVersion: v3
kind: system
spec:
  lifecycle: production
  tier: critical
  components:
    - service:django-celery-app
    - service:postgres
    - datastore:redis
    - datastore:defaultdb
    - datastore:django-celery-db
metadata:
  name: my-django-celery-app
  owner: app-team
  additionalOwners:
    - name: database-team
      type: operator
  tags:
    - foo:bar
---
apiVersion: v3
kind: datastore
metadata:
  name: defaultdb
  additionalOwners:
    - name: db-team
      type: operator
  inheritFrom: system:my-django-celery-app
---
apiVersion: v3
kind: service
metadata:
  name: django-celery-app
  additionalOwners:
    - name: app-team
      type: operator
  links:
    - type: dashboard
      name: Test Dashboard - Service definition
      url: https://app.datadoghq.com/dashboard/p2k-bh9-5s3
---
apiVersion: v3
kind: datastore
metadata:
  name: django-celery-db
---
apiVersion: v3
kind: datastore
metadata:
  name: redis
---
apiVersion: v3
kind: service
metadata:
  name: postgres
